apisix:
  node_listen: 9080
  node_ssl_listen: 9443
  enable_heartbeat: true
  enable_admin: true
  enable_debug: true
  allow_admin:
    - 127.0.0.0/24
  port_admin: 9180
  real_ip_header: "X-Real-IP"
  real_ip_from:
    - 127.0.0.1
  route_idx: 'uri'

etcd:
  host: "http://127.0.0.1:2379"
  prefix: "/apisix"
  timeout: 1

plugins:
  - example-plugin
  - limit-req
  - limit-count
  - key-auth
  - prometheus
  - limit-conn
  - node-status
